In [1]:
from lib.scripts import get_dataframe

In [2]:
df = get_dataframe("TQBR", "TGKB", "2023-01-01", "2023-08-30", "100")

In [5]:
df

,BOARDID,TRADEDATE,SHORTNAME,SECID,NUMTRADES,VALUE,OPEN,LOW,HIGH,LEGALCLOSEPRICE,...,MARKETPRICE2,MARKETPRICE3,ADMITTEDQUOTE,MP2VALTRD,MARKETPRICE3TRADESVALUE,ADMITTEDVALUE,WAVAL,TRADINGSESSION,CURRENCYID,TRENDCLSPR
0,TQBR,2023-01-03,ТГК-2,TGKB,64,814275,0.003540,0.003530,0.003595,0.003530,...,0.003555,0.003555,0.003530,814275,814275,814275.0,0,3,SUR,-0.98
1,TQBR,2023-01-04,ТГК-2,TGKB,131,1482635,0.003550,0.003470,0.003560,0.003510,...,0.003495,0.003495,0.003510,1482635,1482635,1482635.0,0,3,SUR,-0.57
2,TQBR,2023-01-05,ТГК-2,TGKB,864,10890890,0.003515,0.003510,0.003800,0.003565,...,0.003640,0.003640,0.003565,10890890,10890890,10890890.0,0,3,SUR,1.57
3,TQBR,2023-01-06,ТГК-2,TGKB,574,9710645,0.003570,0.003540,0.003730,0.003580,...,0.003635,0.003635,0.003580,9710645,9710645,9710645.0,0,3,SUR,0.14
4,TQBR,2023-01-09,ТГК-2,TGKB,1020,16289580,0.003605,0.003355,0.003870,0.003695,...,0.003710,0.003710,0.003695,16289580,16289580,16289580.0,0,3,SUR,3.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,TQBR,2023-05-22,ТГК-2,TGKB,553,9813005,0.005230,0.005105,0.005285,0.005210,...,0.005215,0.005215,NaN,9813005,9813005,NaN,0,3,SUR,-0.29
96,TQBR,2023-05-23,ТГК-2,TGKB,10613,231164570,0.005500,0.005280,0.005900,0.005340,...,0.005645,0.005645,NaN,231164570,231164570,NaN,0,3,SUR,2.50
97,TQBR,2023-05-24,ТГК-2,TGKB,1300,23254905,0.005365,0.005210,0.005470,0.005280,...,0.005300,0.005300,NaN,23254905,23254905,NaN,0,3,SUR,-1.12
98,TQBR,2023-05-25,ТГК-2,TGKB,11800,257204095,0.005365,0.005295,0.006105,0.005585,...,0.005785,0.005785,NaN,257204095,257204095,NaN,0,3,SUR,5.78
99,TQBR,2023-05-26,ТГК-2,TGKB,2399,45976365,0.005410,0.005230,0.005455,0.005355,...,0.005340,0.005340,NaN,45976365,45976365,NaN,0,3,SUR,-4.12

In [6]:
median = df[['VOLUME']].median()

In [7]:
df[['VOLUME/VOLUME_MEDIAN']] = (df[['VOLUME']] / median)
df[['CLOSE/OPEN']] = (df[['CLOSE']].values / df[['OPEN']].values)
df[['HIGH/LOW']] = (df[['HIGH']].values / df[['LOW']].values)
prepared_df = df[['TRADEDATE', 'OPEN', 'CLOSE', 'VOLUME', 'VOLUME/VOLUME_MEDIAN', 'CLOSE/OPEN', 'HIGH/LOW']]

In [8]:
prepared_df

,TRADEDATE,OPEN,CLOSE,VOLUME,VOLUME/VOLUME_MEDIAN,CLOSE/OPEN,HIGH/LOW
0,2023-01-03,0.003540,0.003530,229000000,0.109832,0.997175,1.018414
1,2023-01-04,0.003550,0.003510,424000000,0.203357,0.988732,1.025937
2,2023-01-05,0.003515,0.003565,2993000000,1.435492,1.014225,1.082621
3,2023-01-06,0.003570,0.003570,2672000000,1.281535,1.000000,1.053672
4,2023-01-09,0.003605,0.003695,4389000000,2.105036,1.024965,1.153502
...,...,...,...,...,...,...,...
95,2023-05-22,0.005230,0.005210,1881000000,0.902158,0.996176,1.035260
96,2023-05-23,0.005500,0.005340,40948000000,19.639329,0.970909,1.117424
97,2023-05-24,0.005365,0.005280,4388000000,2.104556,0.984157,1.049904
98,2023-05-25,0.005365,0.005585,44456000000,21.321823,1.041007,1.152975
99,2023-05-26,0.005410,0.005355,8610000000,4.129496,0.989834,1.043021

In [12]:
buy_df = prepared_df[(prepared_df['VOLUME/VOLUME_MEDIAN'] > 1) & (prepared_df['HIGH/LOW'] > 1)]

In [13]:
buy_df

,TRADEDATE,OPEN,CLOSE,VOLUME,VOLUME/VOLUME_MEDIAN,CLOSE/OPEN,HIGH/LOW
2,2023-01-05,0.003515,0.003565,2993000000,1.435492,1.014225,1.082621
3,2023-01-06,0.003570,0.003570,2672000000,1.281535,1.000000,1.053672
4,2023-01-09,0.003605,0.003695,4389000000,2.105036,1.024965,1.153502
6,2023-01-11,0.003715,0.003810,5042000000,2.418225,1.025572,1.091644
7,2023-01-12,0.003945,0.003915,6505000000,3.119904,0.992395,1.094241
9,2023-01-16,0.003975,0.003820,2098000000,1.006235,0.961006,1.057181
12,2023-01-19,0.003790,0.003815,7882000000,3.780336,1.006596,1.102902
20,2023-01-31,0.003795,0.003860,3128000000,1.500240,1.017128,1.046235
24,2023-02-06,0.003835,0.003865,2331000000,1.117986,1.007823,1.040629
27,2023-02-09,0.003905,0.003920,4690000000,2.249400,1.003841,1.056338
28,2023-02-10,0.003990,0.004950,179780000000,86.225420,1.240602,1.430380
29,2023-02-13,0.005090,0.004630,42888000000,20.569784,0.909627,1.179235
30,2023-02-14,0.004715,0.004330,10643000000,5.104556,0.918346,1.122619
31,2023-02-15,0.004305,0.004120,3965000000,1.901679,0.957027,1.069221
32,2023-02-16,0.004325,0.004220,3330000000,1.597122,0.975723,1.075795
33,2023-02-17,0.004225,0.004180,6777000000,3.250360,0.989349,1.118012
36,2023-02-22,0.004300,0.004370,58865000000,28.232614,1.016279,1.146028
37,2023-02-24,0.004400,0.004370,4155000000,1.992806,0.993182,1.057310
38,2023-02-27,0.004425,0.004530,19674000000,9.435971,1.023729,1.108140
39,2023-02-28,0.004640,0.004740,17176000000,8.237890,1.021552,1.084802
40,2023-03-01,0.004775,0.004700,10160000000,4.872902,0.984293,1.051502
41,2023-03-02,0.004715,0.004590,3998000000,1.917506,0.973489,1.059551
42,2023-03-03,0.004600,0.004580,2796000000,1.341007,0.995652,1.055242
43,2023-03-06,0.004640,0.004660,4660000000,2.235012,1.004310,1.041485
44,2023-03-07,0.004700,0.004660,3842000000,1.842686,0.991489,1.031284
52,2023-03-20,0.004560,0.004620,2959000000,1.419185,1.013158,1.047191
54,2023-03-22,0.004600,0.004705,5000000000,2.398082,1.022826,1.057269
55,2023-03-23,0.004715,0.004770,3766000000,1.806235,1.011665,1.056564
57,2023-03-27,0.004760,0.004715,2137000000,1.024940,0.990546,1.039236
60,2023-03-30,0.004725,0.004860,27622000000,13.247962,1.028571,1.111111
61,2023-03-31,0.004860,0.004735,4201000000,2.014868,0.974280,1.053362
62,2023-04-03,0.004745,0.004735,2672000000,1.281535,0.997893,1.033014
64,2023-04-05,0.004735,0.004845,13302000000,6.379856,1.023231,1.086589
65,2023-04-06,0.004900,0.005175,24266000000,11.638369,1.056122,1.114990
68,2023-04-11,0.005230,0.005060,5893000000,2.826379,0.967495,1.089000
75,2023-04-20,0.005025,0.004980,2164000000,1.037890,0.991045,1.036961
79,2023-04-26,0.005090,0.005180,11234000000,5.388010,1.017682,1.105055
80,2023-04-27,0.005220,0.005110,2114000000,1.013909,0.978927,1.037475
82,2023-05-02,0.005125,0.004955,7417000000,3.557314,0.966829,1.099585
83,2023-05-03,0.004960,0.004745,2661000000,1.276259,0.956653,1.058698
89,2023-05-12,0.004890,0.004690,3086000000,1.480096,0.959100,1.083056
90,2023-05-15,0.004700,0.004900,5824000000,2.793285,1.042553,1.068230
91,2023-05-16,0.004905,0.005490,58709000000,28.157794,1.119266,1.161026
92,2023-05-17,0.005580,0.005130,13541000000,6.494484,0.919355,1.103516
93,2023-05-18,0.005220,0.005125,3963000000,1.900719,0.981801,1.039761
94,2023-05-19,0.005130,0.005225,3631000000,1.741487,1.018519,1.039761
96,2023-05-23,0.005500,0.005340,40948000000,19.639329,0.970909,1.117424
97,2023-05-24,0.005365,0.005280,4388000000,2.104556,0.984157,1.049904
98,2023-05-25,0.005365,0.005585,44456000000,21.321823,1.041007,1.152975
99,2023-05-26,0.005410,0.005355,8610000000,4.129496,0.989834,1.043021